version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  flask-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - mssql
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped

volumes:
  mssql-data: